# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitCount', models.IntegerField(default=0)),
                ('dateStarted', django_jalali.db.models.jDateField(blank=True, editable=False, null=True)),
                ('lastVisit', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
