# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteviews',
            options={'verbose_name': 'شمارنده', 'verbose_name_plural': 'بازدید های سایت'},
        ),
    ]
