# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, upload_to='html/SarmayeTemp/static/mainapp/img/CatIcons/')),
                ('visitCount', models.IntegerField(default=0, null=True, verbose_name='Visit Count')),
                ('lastVisit', django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='Last Viewed by User')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('owner', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('fund', models.CharField(max_length=50, null=True)),
                ('inv_deadline', models.CharField(blank=True, max_length=60)),
                ('expected_gain', models.CharField(blank=True, max_length=5, null=True)),
                ('expected_time', models.CharField(blank=True, max_length=5, null=True)),
                ('visitCount', models.IntegerField(default=0, null=True, verbose_name='Visit Count')),
                ('commentCount', models.IntegerField(default=0, null=True)),
                ('location', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('containInSlideshow', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('damage', models.CharField(blank=True, max_length=200)),
                ('credits', models.CharField(blank=True, max_length=200)),
                ('refund_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('isLegal', models.BooleanField(default=False)),
                ('isFree', models.BooleanField(default=True)),
                ('images', models.ImageField(blank=True, upload_to='html/SarmayeTemp/static/mainapp/img/AdsImgs/')),
                ('proposal', models.FileField(blank=True, upload_to='html/SarmayeTemp/static/mainapp/files/proposals/')),
                ('dateCreated', django_jalali.db.models.jDateField(blank=True, editable=False, null=True)),
                ('lastModified', django_jalali.db.models.jDateField(blank=True, editable=False)),
                ('showInSite', models.BooleanField(default=False, verbose_name='Show in Site')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.AdCategory')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
