# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20170718_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='comment',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
