# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:03
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advertisement_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='fundingStep',
            field=models.CharField(choices=[('1', 'نقد و بررسی فنی'), ('2', 'جلسه ارزیابی اقتصادی'), ('3', 'معرفی به سرمایه گذار'), ('4', 'عقد قرارداد')], default=1, max_length=30, verbose_name='Step'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to=ads.models.AdCategory.CatImage_directory_path),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='images',
            field=models.ImageField(blank=True, upload_to=ads.models.Advertisement.AdImage_directory_path),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='proposal',
            field=models.FileField(blank=True, upload_to=ads.models.Advertisement.AdFile_directory_path),
        ),
    ]
