# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20170807_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='fundingStep',
            field=models.CharField(blank=True, choices=[('1', 'نقد و بررسی فنی'), ('2', 'جلسه ارزیابی اقتصادی'), ('3', 'معرفی به سرمایه گذار'), ('4', 'عقد قرارداد')], max_length=30, verbose_name='Step'),
        ),
    ]
