# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_auto_20170807_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='fundingStep',
            field=models.CharField(choices=[('0', 'نقد و بررسی فنی'), ('1', 'جلسه ارزیابی اقتصادی'), ('2', 'معرفی به سرمایه گذار'), ('3', 'عقد قرارداد')], default=None, max_length=30, verbose_name='Request'),
        ),
    ]
