# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20170807_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='isEval',
            field=models.BooleanField(default=False),
        ),
    ]
