# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_advertisement_iseval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='dateCreated',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='fund',
            field=models.CharField(max_length=50, null=True, verbose_name='کسری سرمایه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='fundingStep',
            field=models.CharField(blank=True, choices=[('0', 'نقد و بررسی'), ('1', 'ارزیابی اقتصادی'), ('2', 'معرفی به سرمایه گذار'), ('3', 'عقد قرارداد')], max_length=30, null=True, verbose_name='آخرین درخواست'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='isEval',
            field=models.BooleanField(default=False, verbose_name='برچسب تایید'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='owner',
            field=models.CharField(max_length=30, null=True, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='requestDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آخرین درخواست'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='showInSite',
            field=models.BooleanField(default=False, verbose_name='نمایش در سایت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=400, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='visitCount',
            field=models.IntegerField(default=0, null=True, verbose_name='بازدید'),
        ),
    ]
