# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:40
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20170807_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='review',
            field=models.FileField(blank=True, upload_to=ads.models.Advertisement.AdFile_directory_path),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='fundingStep',
            field=models.CharField(blank=True, choices=[('0', 'نقد و بررسی'), ('1', 'ارزیابی اقتصادی'), ('2', 'معرفی به سرمایه گذار'), ('3', 'عقد قرارداد')], max_length=30, null=True, verbose_name='آخرین '),
        ),
    ]
