# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:43
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_auto_20170808_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='review',
            field=models.FileField(blank=True, upload_to=ads.models.Advertisement.review_directory_path),
        ),
    ]
