# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_auto_20170808_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='isInvited',
            field=models.BooleanField(default=False, verbose_name='تایید'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='isEval',
            field=models.BooleanField(default=False, verbose_name='تایید نقد'),
        ),
    ]
