# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_auto_20170808_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='isInvited',
            field=models.BooleanField(default=False, verbose_name='تایید جلسه'),
        ),
    ]
