# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 01:20
from __future__ import unicode_literals

import ads.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_auto_20170808_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.AdCategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='containInSlideshow',
            field=models.BooleanField(default=True, verbose_name='نمایش در اسلاید'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='fund',
            field=models.CharField(max_length=50, null=True, verbose_name='مبلغ سرمایه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='fundingStep',
            field=models.CharField(blank=True, choices=[('0', 'نقد و بررسی'), ('1', 'جلسه ارزیابی اقتصادی'), ('2', 'معرفی به سرمایه گذار'), ('3', 'عقد قرارداد')], max_length=30, null=True, verbose_name='آخرین درخواست'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='owner',
            field=models.CharField(max_length=30, null=True, verbose_name='صاحب طرح'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='review',
            field=models.FileField(blank=True, upload_to=ads.models.Advertisement.review_directory_path, verbose_name='فایل نقد'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='summary',
            field=models.TextField(blank=True, verbose_name='شرح'),
        ),
    ]
