# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_auto_20170809_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='isEval',
            new_name='isReviewOK',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='isInterviewPassed',
            field=models.BooleanField(default=False, verbose_name='تایید جلسه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='isInvited',
            field=models.BooleanField(default=False, verbose_name='دعوت به جلسه'),
        ),
    ]
