# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_auto_20170809_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='isContracted',
            field=models.BooleanField(default=False, verbose_name='عقد قرارداد'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='isPresented',
            field=models.BooleanField(default=False, verbose_name='معرفی به سرمایه گذار'),
        ),
    ]
