# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_auto_20170809_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='isInterviewPassed',
            new_name='isInterviewOK',
        ),
    ]
