# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 01:46
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_auto_20170809_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='InvitationDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ جلسه'),
        ),
    ]
