# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_auto_20170809_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='requestDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین درخواست'),
        ),
    ]
