# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_auto_20170812_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='گزارش'),
        ),
    ]
