# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_auto_20170815_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='isReviewOK',
            field=models.BooleanField(default=False, verbose_name='تایید نقد - مهرتایید'),
        ),
    ]
