# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_auto_20170816_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='investor',
            field=models.ManyToManyField(blank=True, to='ads.Investor', verbose_name='سرمایه گذار'),
        ),
    ]
