# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_auto_20170816_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'طرح', 'verbose_name_plural': 'طرح ها'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
    ]
