# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0036_auto_20170816_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='isPaid',
            field=models.BooleanField(default=False, verbose_name='پرداخت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='paidAmount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='isReviewOK',
            field=models.BooleanField(default=False, verbose_name='تایید نقد'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='showInSite',
            field=models.BooleanField(default=False, verbose_name='نمایش'),
        ),
    ]
