# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0037_auto_20170819_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='interviewReport',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='گزارش جلسه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='report',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='گزارش نقد'),
        ),
    ]
