# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0041_auto_20170829_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='commentAboutUs',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
