# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 12:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0043_auto_20170829_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='fundUsage',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='نحوه استفاده از سرمایه جذب شده'),
        ),
    ]
