# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0044_auto_20170829_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='executiveSummary',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='خلاصه اجرایی طرح'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='fundUsage',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='نحوه استفاده از سرمایه جذب شده'),
        ),
    ]
