# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0046_auto_20170829_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='isReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
