# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0047_advertisement_isreviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='isReviewed',
            field=models.BooleanField(default=False, verbose_name='نقد شده'),
        ),
    ]
