# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0048_auto_20170829_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='benefitShare',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='نحوه تقسیم سود'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='compet',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='مزیت رقابتی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='marketSize',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='اندازه بازار'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='marketingPlan',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='برنامه بازاریابی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='presentCustomers',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='مشتریان فعلی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rateOfReturn',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='نرخ بازگشت سرمایه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='damage',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='زیان\u200cدهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='presentIncome',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='درآمد سالیانه'),
        ),
    ]
