# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:44
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0049_auto_20170902_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='proposal',
            field=models.FileField(blank=True, null=True, upload_to=ads.models.Advertisement.AdFile_directory_path, verbose_name='پروپوزال'),
        ),
    ]
