# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0050_auto_20170904_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='marketingPlan',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='برنامه بازاریابی'),
        ),
    ]
