# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0051_auto_20170904_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='refund_duration',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='benefitShare',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='نحوه تقسیم سود'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='compet',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='مزیت رقابتی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='credits',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='نحوه ضمانت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='damage',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='زیان\u200cدهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='estimatedCosts',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='هزینه های پیش بینی شده'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='executiveSummary',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='خلاصه اجرایی طرح'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='fundUsage',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='نحوه استفاده از سرمایه جذب شده'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='investorShare',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='درصد مشارکت سرمایه گذار'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='marketSize',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='اندازه بازار'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='presentCustomers',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='مشتریان فعلی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='presentIncome',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='درآمد سالیانه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rateOfReturn',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='نرخ بازگشت سرمایه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='resume',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='سابقه کاری'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='revenueModel',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='مدل درآمدی'),
        ),
    ]
