# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 09:55
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0057_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='review',
            field=models.FileField(blank=True, null=True, upload_to=ads.models.Advertisement.review_directory_path, verbose_name='فایل نقد'),
        ),
    ]
