# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0058_auto_20170919_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='isBest',
            field=models.BooleanField(default=False, verbose_name='بهترینها'),
        ),
    ]
