# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-07 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_isinvestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
